language: node_js
node_js:
- "10"

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish --access public"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - glib.briia@gmail.io
    on_success: change
    on_failure: always