language: node_js
node_js:
- "10"

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && chmod +x ./bin/cli.js && npm publish --access public"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - glib.briia@gmail.com
    on_success: change
    on_failure: always
